spring:
  application:
    name: RCS-V1
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/rcsv1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    servlet:
      multipart:
        #最大单个文件大小
        max-file-size: 10MB
        #最大请求大小(包括所有文件和表单数据)
        max-request-size: 100MB

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug